<a href="https://colab.research.google.com/github/ehtesam75/Machine-learning-notes/blob/main/Numpy/Numpy_advanced.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### numpy array vs python list

### speed

In [ ]:
#speed
#list
a = [i for i in range(1000000)]
b = [i for i in range(1000000, 20000000)]
c = []

#measure time
import time

start = time.time()
for i in range(len(a)):
  c.append(a[i] + b[i])
end = time.time();
print(end-start)    #seconds

0.1857740879058838


In [ ]:
#in numpy
import numpy as np

a = np.arange(10000000)
b = np.arange(10000000, 20000000)

start = time.time()
c = a + b
end = time.time();
print(end-start)

0.04723691940307617


### memory usage

In [ ]:
#memory
a = [i for i in range(100000000)]

import sys
sys.getsizeof(a)  #in byte

835128600

In [ ]:
#in numpy
a = np.arange(100000000)
sys.getsizeof(a)

800000112

In [ ]:
#using int32 in numpy
a = np.arange(10000000, dtype = np.int32)
sys.getsizeof(a)
#using np.int16/8 will have lower size

40000112

### fancy indexing

In [ ]:
a = np.arange(12).reshape(4, 3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
#get 1st, 3rd, 4th row; can't do normal indexing like a[::2]
a[[0, 2, 3]]

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
a[:, [0, 2]]
#to get specific cols

array([[ 0,  2],
       [ 3,  5],
       [ 6,  8],
       [ 9, 11]])

### boolean indexing

In [ ]:
#boolean indexing : filtering data based on given condition
a = np.random.randint(1, 100, 24).reshape(6, 4)
#random 24 num from 1 to 100
a

array([[30, 91, 64, 52],
       [28, 27, 69, 77],
       [50, 46, 91,  2],
       [91, 42, 67, 86],
       [93, 16, 87, 66],
       [73, 20, 40, 39]])

In [ ]:
#find all num grater than 50
a > 50

array([[False,  True,  True,  True],
       [False, False,  True,  True],
       [False, False,  True, False],
       [ True, False,  True,  True],
       [ True, False,  True,  True],
       [ True, False, False, False]])

In [ ]:
a[a > 50]

array([91, 64, 52, 69, 77, 91, 91, 67, 86, 93, 87, 66, 73])

In [ ]:
a[a % 2 == 0] #even

array([30, 64, 52, 28, 50, 46,  2, 42, 86, 16, 66, 20, 40])

In [ ]:
a[(a > 50) & (a % 2 == 0)]

array([64, 52, 86, 66])

In [ ]:
a[~(a % 7 == 0)] #not divisable by 7

array([30, 64, 52, 27, 69, 50, 46,  2, 67, 86, 93, 16, 87, 66, 73, 20, 40,
       39])

### brodcasting
Broadcasting is a way to perform operations on arrays of different shapes.

NumPy automatically “expands” the smaller array to match the bigger one.

### brodcasting rules

✅ Rule 1: Right-to-left comparison

Shapes are compared starting from the last (rightmost) dimension and moving left.
If one array has fewer dimensions, it is treated as if it has leading dimensions of size 1.

✅ Rule 2: Dimension compatibility

For each dimension, sizes are compatible only if:

They are equal, OR
One of them is 1

✅ Rule 3: Expansion of dimension 1

If a dimension is 1, it is stretched (broadcasted) to match the size of the other array in that dimension.
This expansion is conceptual (no actual data copying needed internally).

❌ Rule 4: Incompatibility leads to error

If in any dimension:

sizes are different and
neither is 1

→ broadcasting fails and NumPy raises an error.

### brodcasting example

In [ ]:
a = np.arange(12).reshape(3, 4)
b = np.arange(4).reshape(4)
print(a)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2 3]


In [ ]:
a + b

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14]])

In [ ]:
#more example
a = np.arange(12).reshape(3, 4)
b = np.arange(4).reshape(1, 4)
print(a)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 1 2 3]]


In [ ]:
a = np.arange(12).reshape(3, 4)
b = np.arange(3)
print(a)
print(b)
print(a + b)
#error (3, 4) + (3, 3) brodcast not possible

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2]


ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [ ]:
a = np.arange(3).reshape(1, 3)
b = np.arange(3).reshape(3, 1)
print(a)
print(b)
print(a + b)
#sucess : (3, 3) + (3, 3)..every 1 will scaled up to 3

[[0 1 2]]
[[0]
 [1]
 [2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [ ]:
a = np.arange(4).reshape(1, 4)
b = np.arange(3).reshape(3, 1)
print(a)
print(b)
print(a + b) #(3, 4) + (3, 4)

[[0 1 2 3]]
[[0]
 [1]
 [2]]
[[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]]


In [ ]:
a = np.arange(1)
# first (1, 1)
#then (2, 2)
b = np.arange(4).reshape(2, 2)
print(a)
print(b)
print(a + b) #(2, 2) + (2, 2)

[0]
[[0 1]
 [2 3]]
[[0 1]
 [2 3]]


In [ ]:
a = np.arange(12).reshape(3, 4)
b = np.arange(12).reshape(4, 3)
print(a)
print(b)
print(a + b) #error

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [ ]:
a = np.arange(16).reshape(4, 4)
b = np.arange(4).reshape(2, 2)
print(a)
print(b)
print(a + b) #error

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1]
 [2 3]]


ValueError: operands could not be broadcast together with shapes (4,4) (2,2) 

### working with math formula

In [ ]:
a = np.arange(3, 10)
print(a)
np.sum(a)

[3 4 5 6 7 8 9]


np.int64(42)

In [ ]:
np.sin(a)

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ,
        0.98935825,  0.41211849])

### sigmoid

sigmoid formula : σ(x) = 1 / (1 + e^(-x))

In [ ]:
#custom function to calculate sigmoid (all output is in range of 0 to 1 )
def sigmoid(arr):
  return 1/(1 + np.exp(-arr))
  #NumPy automatically applies operations element
  #So even though i passed an array, the function works on every element

a = np.arange(12)
sigmoid(a)

array([0.5       , 0.73105858, 0.88079708, 0.95257413, 0.98201379,
       0.99330715, 0.99752738, 0.99908895, 0.99966465, 0.99987661,
       0.9999546 , 0.9999833 ])

###loss function
A loss function measures how wrong your model is

### mean squared error

MSE = loss function for regression

Penalizes large errors more than small ones

Always non-negative

MSE = (1/n) * Σ (y_true - y_pred)²

In [ ]:
actual = np.random.randint(1, 50, 25)
predicted = np.random.randint(1, 50, 25)
print(actual)
print(predicted)

[ 3  6  1 12 36 30  1 49 42 31 18  4 10 45 26 17 16 34 47 15 46 20 19 14
 13]
[47 24 12 34  1  3 25  6 39 29 28 20 44 31 13  8 29 12 33 32 12 14 14 11
 19]


In [ ]:
def mse(acutal, predicted):
  return np.mean((actual - predicted) ** 2)

mse(actual, predicted)

np.float64(464.6)

### Categorical Cross-Entropy
Categorical Cross-Entropy = loss for multi-class classification

measures difference between true label and predicted probability

CCE = - Σ (y_true * log(y_pred))

In [ ]:
actual = np.array([1, 0, 0])
predicted = np.array([0.8, 0.1, 0.1])

def cce(actual, predicted):
  s = np.sum(actual * np.log(predicted))
  return -1 * s

cce(actual, predicted)

np.float64(0.2231435513142097)

### binary cross entropy

BCE = loss function for binary classification

Works with sigmoid activation

Output must be probability (0–1)



bce formula = - Σ [ y log(p) + (1 - y) log(1 - p) ]

In [ ]:
def bce(actual, predicted):
  s = np.sum(actual *np.log(predicted) + (1 - actual) * np.log(1 - predicted))
  return -1 * s

bce(actual, predicted)

np.float64(0.43386458262986227)