<a href="https://colab.research.google.com/github/ehtesam75/Machine-learning-notes/blob/main/Numpy/Numpy_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### why numpy is faster

 NumPy is faster because:
 - Uses C internally
 - Avoids Python loops (vectorization)
 - Uses contiguous memory
 - Fixed data types

###numpy array


In [ ]:
import numpy as np
a = np.array([1, 2])
print(a)

[1 2]


### 2d, 3d array

In [ ]:
b = np.array([[1, 2], [3, 4]])
print('2D array:')
print(b)

c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print('\n3D array:')
print(c)

2D array:
[[1 2]
 [3 4]]

3D array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


###arange

In [ ]:
np.arange(1, 5, 2)

array([1, 3])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

###with reshape

In [ ]:
np.arange(1, 9, 2).reshape(2, 2)

array([[1, 3],
       [5, 7]])

### ones, zeros, random

In [ ]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
np.random.random((3, 2))
# np.random is a module, and random() is a function inside that module

array([[0.91373267, 0.67113859],
       [0.85962991, 0.9593906 ],
       [0.60872753, 0.99741973]])

### linspace

In [ ]:
np.linspace(1, 9, 4)
#default value float

array([1.        , 3.66666667, 6.33333333, 9.        ])

In [ ]:
np.linspace(0, 10, 5, dtype = int)

array([ 0,  2,  5,  7, 10])

### identity

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### ndim

In [ ]:
a1 = np.arange(10, dtype = np.int32)
a2 = np.arange(12, dtype = float).reshape(3, 4)
a3 = np.arange(8, dtype = float).reshape(2, 2, 2)

In [ ]:
#dimension
a1.ndim

1

In [ ]:
a3.ndim

3

### shape

In [ ]:
a2.shape
#tells row, col

(3, 4)

In [ ]:
a3.shape
# A 3D array is basically a collection of multiple 2D arrays, just like 2d array is a collection of multiple 1d array
# (2, 2, 2) → (depth, rows, columns)
# 2 → number of 2D arrays
# 2 → number of rows
# 2 → number of columns

(2, 2, 2)

### size

In [ ]:
a2.size

12

### item size

In [ ]:
a3.itemsize
# Returns the size (in bytes) of each element in the array (not the whole array)
# For example, int64 → 8 bytes, int32 → 4 bytes

8

### dtype

In [ ]:
a1.dtype

dtype('int32')

In [ ]:
a3.dtype

dtype('float64')

### changing size

In [ ]:
a2.astype(np.int32)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)

### array operation (scalar operation)

In [ ]:
a1 = np.arange(12).reshape(3, 4)
a2 = np.arange(12, 24).reshape(3, 4)

### arithmatic operation

In [ ]:
# Scalar operation means performing an operation on each element using a single value
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [ ]:
#relational
a1 > 5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

### vector operation

In [ ]:
# Vector operation means performing an operation on each element using another array (element-wise)
#arithmatic
a1 * a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

### array operation

In [ ]:
a1 = np.random.random((3, 3))   # 3x3 matrix with values between 0 and 1
a1 = np.round(a1 * 100)         # scale to 0–100 and round
a1

array([[95., 75., 93.],
       [92., 13., 46.],
       [18., 38.,  8.]])

### max/min/sum/prod

In [ ]:
np.prod(a1)

np.float64(199481634144000.0)

### row/col wise operation

In [ ]:
#0 -> col and 1 -> row
np.min(a1, axis = 1)

array([75., 13.,  8.])

### mean/median/std/var

In [ ]:
np.mean(a1)
np.median(a1, axis = 0)
#std -> standerd deviation
#var -> variance


array([92., 38., 46.])

### trigonometric fucntion

In [ ]:
np.sin(a1)

array([[ 0.68326171, -0.38778164, -0.94828214],
       [-0.77946607,  0.42016704,  0.90178835],
       [-0.75098725,  0.29636858,  0.98935825]])

###dot product

In [ ]:
#first's col has to be == second's row number
# 3 x 4 and 4 x 3 (valid condition for dot product)
#output will be in 3 x 3

a1 = np.arange(12).reshape(3, 4)
a2 = np.arange(12, 24).reshape(4, 3)
np.dot(a1, a2)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

###log and exponents

In [ ]:
np.log(a1)
np.exp(a2)

/tmp/ipykernel_6739/1346601788.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a1)


array([[1.62754791e+05, 4.42413392e+05, 1.20260428e+06],
       [3.26901737e+06, 8.88611052e+06, 2.41549528e+07],
       [6.56599691e+07, 1.78482301e+08, 4.85165195e+08],
       [1.31881573e+09, 3.58491285e+09, 9.74480345e+09]])

### round/floor/ceil

In [ ]:
np.round(np.random.random((2, 3)) * 100) #round of to the nearest int

array([[77., 59.,  4.],
       [21., 96., 73.]])

In [ ]:
np.floor(6.9)
np.round(6.5)
np.ceil(7.1)

np.float64(8.0)

### indexing

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3, 4)
a3 = np.arange(8).reshape(2, 2, 2)
a2


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a1[0]
a1[-1] #last item


np.int64(9)

In [ ]:
a2[2, 2] #row, col

np.int64(10)

In [ ]:
a3[1, 0, 1]

np.int64(5)

### slicing

In [ ]:
a1[2:5] #from index 2 to 4

array([2, 3, 4])

In [ ]:
a1[1:7:2] #after 2 items each time

array([1, 3, 5])

In [ ]:
# in 2d
#get first row
a2[0, :]

array([0, 1, 2, 3])

In [ ]:
#get 3rd col
a2[ :,2]

array([ 2,  6, 10])

In [ ]:
#get 5, 6, 9, 10 form a2
a2[1:, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
#get elemtns form 4 corners from a2
a2[::2, ::3]

array([[ 0,  3],
       [ 8, 11]])

In [ ]:
#get 1, 3 and 9, 11 form a2
a2[::2, 1::2]

array([[ 1,  3],
       [ 9, 11]])

In [ ]:
a2[1, ::3]

array([4, 7])

In [ ]:
a2[0:2, 1:]

array([[1, 2, 3],
       [5, 6, 7]])

### slicing with 3d array

In [ ]:
a3 = np.arange(27).reshape(3, 3, 3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[0, 1, :]

array([3, 4, 5])

In [ ]:
a3[2, 1:, 1:]

array([[22, 23],
       [25, 26]])

In [ ]:
a3[::2, 0, ::2]

array([[ 0,  2],
       [18, 20]])

### iterating

In [ ]:
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [ ]:
#print all elemnets in 3d array
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### reshaping

In [ ]:
a1.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### transpose

In [ ]:
np.transpose(a2)
a2.T #shortcut

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

### ravel

In [ ]:
#ravel
#convert any dimention to 1d array
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### horizontal stakcing

In [ ]:
a4 = np.arange(12).reshape(3, 4)
a5 = np.arange(12, 24).reshape(3, 4)
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### verticle stakcing

In [ ]:
np.hstack((a4, a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
np.vstack((a4, a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

###horizontal spliting

In [ ]:
np.hsplit(a4, 2) #will split in 2 equal part

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

### verticle spliting

In [ ]:
np.vsplit(a4, 3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]